Feature/oop herencia polimorfismo vehiculos readme
programacion-avanzada/workspace pull request #15
Opened 2020-10-22 00:11 UTC by Mel-A

Desde el grupo nombreEnCamelCase se envia el cambio al readme

2020-10-24 13:35 UTC, delucas requested changes
Me gustan los aportes. El texto es claro y conciso. Agregué mínimas revisiones.
Lo más importante es corregir el diagrama de clases.

2020-10-24 13:35 UTC, delucas commented on oop-herencia-polimorfismo-vehiculos/README.md
> +![version](https://img.shields.io/static/v1?label=version&message=v0.1&color=green) ![tamanio](https://img.shields.io/static/v1?label=tamanio&message=6.36kb&color=green) ![contribuciones](https://img
Los shields son bonitos y útiles, pero siempre y cuando se mantengan actualizados automáticamente.
¿Sugieren alguna estrategia de actualización?

2020-10-24 13:35 UTC, delucas commented on oop-herencia-polimorfismo-vehiculos/README.md
>  ## Características especiales del problema
Yo le cambiaría el nombre a este por "puntos de extensión"

2020-10-24 13:35 UTC, delucas commented on oop-herencia-polimorfismo-vehiculos/README.md
> +* Por favor a cada cambio que agregues no olvides mantener el test coverage!
Falta el signo de exclamación que abre ;)

2020-10-24 13:35 UTC, delucas commented on oop-herencia-polimorfismo-vehiculos/README.md
> +![diagrama-de-clases](assets/diagrama-de-clases.jpeg)
El diagrama de clases tiene los estereotipos erróneos. La herencia no se ilustra así, sino con el triángulo vacío apuntando hacia la superclase.

2020-10-31 14:17 UTC, delucas commented on oop-herencia-polimorfismo-vehiculos/README.md
> +![version](https://img.shields.io/static/v1?label=version&message=v0.1&color=green) ![tamanio](https://img.shields.io/static/v1?label=tamanio&message=6.36kb&color=green) ![contribuciones](https://img
¿Cómo van a resolver esto?

2020-11-08 00:25 UTC, Mel-A commented on oop-herencia-polimorfismo-vehiculos/README.md
> +![version](https://img.shields.io/static/v1?label=version&message=v0.1&color=green) ![tamanio](https://img.shields.io/static/v1?label=tamanio&message=6.36kb&color=green) ![contribuciones](https://img
Se agrego un packaje.json para mantener el shield de version updateado. Lo probamos en nuestro repositorio.
saludos!

2020-12-05 14:16 UTC, merged