Add README.md, jerarquiaexcepciones.png
programacion-avanzada/workspace pull request #17
Opened 2020-10-22 21:10 UTC by jony91mr

Pull Request KerberosSW. basicas-excepciones

2020-10-24 13:45 UTC, delucas requested changes
- Me gusta esta primera versión
- Faltaría mencionar las fuentes. Quizás incluso enlazar algunas páginas de la documentación de Java.
- Ya que van a editar el archivo, cambiaría "test" por "prueba", siempre que se pueda y no pierda sentido la frase.
- Por último, cuando mencionen clases de Java, escríbanlas entre comillas oblicuas, para que queden así: `String`. Es lo más usual y transmite mucha información al lector.

2020-10-24 13:45 UTC, delucas commented on basicas-excepciones/README.md
> +![](jerarquiaexcepciones.png)
Encontré esta [imagen aquí](https://www.google.com/search?safe=off&sa=G&hl=en&sxsrf=ALeKk02QKt1hprFR47HfVpARAiVeNHP3hQ:1603546895802&q=jerarquia+de+excepciones+en+java&tbm=isch&source=iu&ictx=1&tbs=simg:CAESoAIJSOmLFxAGlNAalAILELCMpwgaYgpgCAMSKOwCixPuB4oTvxPmB4AT6weCE7sTyzbJNsg2yjbGNo03zT_1HNos34z0aMAvHQ4IzCNZT4Zuc3y1yRywzZ8EpoKDOq1aBAic9np_1Gor6LBtdc5Egkng24o8nCWiAEDAsQjq7-CBoKCggIARIEZAkYQgwLEJ3twQkajAEKGwoIZG9jdW1lbnTapYj2AwsKCS9tLzAxNWJ2MwodCgpzY3JlZW5zaG902qWI9gMLCgkvbS8wMXpibncKGAoGbnVtYmVy2qWI9gMKCggvbS8wNWZ3YgoYCgZvcmFuZ2XapYj2AwoKCC9tLzBqY19wChoKB2Nhcm1pbmXapYj2AwsKCS9tLzA1dF95dAw&fir=MTytJRfRhg0MxM%252Ce9xdLYWHVAr2fM%252C_&vet=1&usg=AI4_-kQUp-VW_BUxkV4H8s5fzkJbDa9VZg&ved=2ahUKEwi-ievYrc3sAhUFH7kGHQH-BsEQ9QF6BAgGEAQ&biw=2560&bih=1279#imgrc=MTytJRfRhg0MxM). Podrían realizar una propia, o atribuir al autor original.

2020-10-24 13:45 UTC, delucas commented on basicas-excepciones/README.md
> +Se podrían realizar un test donde se cree una excepción propia que pueda lanzar excepciones del tipo no verificadas
Esta frase no queda clara

2020-10-24 13:45 UTC, delucas commented on basicas-excepciones/README.md
> +Se demuestra como la División por cero lanza una excepción del tipo arithmeticException , y para poder comprobarlo a través del test, se indica en la línea 12 que esperamos que sea lanzada una excepc
`ArithmeticException`

2020-10-26 18:43 UTC, IorioDiego commented
[KerberosSW] se agregaron las fuentes de donde fueron obtenidas la imagen y la información. Se resaltó las clases de Java y se cambio la palabra "test" por "prueba"

2020-10-31 14:16 UTC, merged