[Stibitz256] actualización del README.md
programacion-avanzada/workspace pull request #19
Opened 2020-10-24 05:45 UTC by matiass

2020-10-24 14:04 UTC, delucas requested changes
Me gusta el trabajo que hicieron. Tiene algunos puntos de mejora que señalé en mensajes individuales.

2020-10-24 14:04 UTC, delucas commented on complejidad-computacional-street-numbers/README.md
> +| StreetNumbersStrategy | |
No se si una tabla es la mejor forma de mostrar esta información. Queda muy ancha. Quizás una enumeración. Prueben y vean cuál va mejor.

2020-10-24 14:04 UTC, delucas commented on complejidad-computacional-street-numbers/README.md
> +<p align="center">
Las imágenes se insertan directamente con markdown, no es necesario utilizar HTML.

2020-10-24 14:04 UTC, delucas commented on complejidad-computacional-street-numbers/README.md
> +Al evaluar las distintas complejidades computacionales que tienen las distintas estrategias se puede comprobar que la Estrategia 1 tiene un complejidad del tipo O(N * (posición *N)) la cual hará que
¿ Poisición x N, o posición + N ?

2020-10-24 14:04 UTC, delucas commented on complejidad-computacional-street-numbers/README.md
> +<p align="center">
De hechoi, la deben enlazar con una ruta relativa al archivo README.md, la ruta proporcionada no va a funcionar una vez que se acepte el PR

2020-10-24 14:04 UTC, delucas commented on complejidad-computacional-street-numbers/README.md
> +Este proyecto me permite obtener el resultado al sumar las distintas posiciones mientras avanza a su lado izquierdo  o su lado derecho, yendo hasta el final y regresando.
¿Podrían explicar esto un poco mejor?
Aquí tienen un [ejemplo de este mismo problema](https://algorithmist.com/wiki/UVa_138_-_Street_Numbers). Agréguenlo como fuente también, a este enlace.

2020-10-25 00:32 UTC, matiass commented on complejidad-computacional-street-numbers/README.md
> +| StreetNumbersStrategy | |
Se quita la tabla!

2020-10-25 00:33 UTC, matiass commented on complejidad-computacional-street-numbers/README.md
> +<p align="center">
Se hace uso del markdown y se hace referencia a la ubicación relativa.

2020-10-25 00:33 UTC, matiass commented on complejidad-computacional-street-numbers/README.md
> +Al evaluar las distintas complejidades computacionales que tienen las distintas estrategias se puede comprobar que la Estrategia 1 tiene un complejidad del tipo O(N * (posición *N)) la cual hará que
Se modifica por posición + N.

2020-10-25 00:34 UTC, matiass commented on complejidad-computacional-street-numbers/README.md
> +Este proyecto me permite obtener el resultado al sumar las distintas posiciones mientras avanza a su lado izquierdo  o su lado derecho, yendo hasta el final y regresando.
Se hace un pequeño resumen de números de calle y se agrega el hipervínculo en el titular.

2020-10-31 14:20 UTC, merged