OIA: Computando patentes
programacion-avanzada/workspace pull request #2
Opened 2020-05-11 22:10 UTC by Federico-G

2020-05-11 22:45 UTC, delucas requested changes
La esencia es la correcta, me parece bien.
Hice comentarios cosméticos y de implementación.

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Conversor1995.java
> +		char[] p = patente.toCharArray();
En general, pero lo digo aquí primero, nos conviene tener nombres de variables más descriptivos

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Conversor1995.java
> +		n += (p[0] - 65) * 676_000;
Estas constantes mágicas no se entiende bien de dónde salen. Yo usaría alias para esas constantes, o las cuentas que lo generan.
Sobre todo 48, 65, y las ultimas tres

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Conversor1995.java
> +		p[5] = (char) (n + 48);
mismos comentarios, pero al revés

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Conversor2016.java
> +		return new String(p);
Todo lo mismo que para la otra estrategia

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Main.java
> +package computando_patentes;
Los paquetes se nombran con camel case también

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Main.java
> +public class Main {
Este main se te chispoteó, porque venimos usando tests :)

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Patente.java
> +		return conversor.getPatente(patenteNumero + n);
Para mi, deberia devolver una Patente

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Conversor.java
> +		return c;
Este nombre de variables es raro...

2020-05-11 22:45 UTC, delucas commented on oia/computando_patentes/src/computando_patentes/Conversor.java
> +	public static Conversor getConversor(String patente) {
La patente que enviaría, ya que estamos, es el objeto Patente y no el String

2020-05-12 19:48 UTC, delucas commented on oia/computando_patentes/src/computandoPatentes/Patente.java
> +		long patenteNumero = conversor.getNumero(this);
El conversor ya conoce a this... para qué se lo pasás de nuevo? :thinking:

2020-05-12 19:48 UTC, delucas commented on oia/computando_patentes/src/computandoPatentes/Conversor.java
> +	protected final int NUMEROS3 = NUMEROS2 * NUMEROS;
Jajaja muy literal fue lo tuyo :P

2020-05-12 19:49 UTC, Federico-G commented on oia/computando_patentes/src/computandoPatentes/Conversor.java
> +	protected final int NUMEROS3 = NUMEROS2 * NUMEROS;
😉

2020-05-12 19:52 UTC, delucas approved these changes

2020-05-12 19:52 UTC, merged