[LosCobit]Agregando Readme
programacion-avanzada/workspace pull request #26
Opened 2020-10-25 00:52 UTC by fsabes

[LosCobit]Agregando Readme

2020-10-31 14:11 UTC, delucas requested changes
Mayormente está bueno el README, tiene algunos errores de tipeo, formato y redacción que estaría bueno corregir antes de incorporarlos. Y hay archivos que deben remover del PR (.classpath y .project).

Por favor hagan otra pasada y realicen un comentario cuando esté para revisar.

2020-10-31 14:11 UTC, delucas commented on basicas-entrada-salida/README.md
> +- El sistema de entrada/salida en Java. Usa la abstracción del flujo (stream) para tratar la comunicación de información entre el programa y el exterior (teclado, pantalla, archivos, sockets de red,
Hay errores de redacción en este párrafo. Y puntuación. Y acentuación.

2020-10-31 14:11 UTC, delucas commented on basicas-entrada-salida/README.md
> +![](https://github.com/fsabes/testreadme/blob/main/img.jpg)
Agreguen la imagen al PR y referéncienla en forma local, no con la ruta completa.

2020-10-31 14:11 UTC, delucas commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Este archivo no debería estar en el PR

2020-10-31 14:11 UTC, delucas commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Este archivo no corresponde al PR.

2020-10-31 14:11 UTC, delucas commented on basicas-entrada-salida/README.md
> +Creamos la clase **archivo** que tiene un atributo de tipo `String`.
```suggestion
Creamos la clase `Archivo` que tiene un atributo de tipo `String`.
```

2020-10-31 14:11 UTC, delucas commented on basicas-entrada-salida/README.md
> +```
Este fragmento de código está incompleto. Falta la llave de cierre. Y necesita mejorar la tabulación.

2020-10-31 14:11 UTC, delucas commented on basicas-entrada-salida/README.md
> +	}
Cuidado con la tabulación de este bloque de código

2020-10-31 14:11 UTC, delucas commented on basicas-entrada-salida/README.md
> +```
Este fragmento está perfecto :100:

2020-11-03 00:47 UTC, fsabes commented on basicas-entrada-salida/README.md
> +- El sistema de entrada/salida en Java. Usa la abstracción del flujo (stream) para tratar la comunicación de información entre el programa y el exterior (teclado, pantalla, archivos, sockets de red,
Profe. hicimos las correcciones. Y la imagen también la subimos.

2020-11-07 14:59 UTC, delucas requested changes
Sólo dos pavadas, y estamos :)

2020-11-07 14:59 UTC, delucas commented on basicas-entrada-salida/README.md
> +}
```suggestion
public class Archivo {
	private String nombre;
	public Archivo(String nombre) { //Constructor
		this.nombre = nombre;
	}
}
```

2020-11-07 14:59 UTC, delucas commented on basicas-entrada-salida/README.md
> +![](img.jpg)
¿Tienen la fuente de esta imagen? Habría que citarla

2020-12-05 14:16 UTC, merged