Ejercicio de OIA - Armando Móviles -
programacion-avanzada/workspace pull request #7
Opened 2020-06-05 01:03 UTC by hlanzillotta

Archivo comprimido que contiene el enunciado, el diagrama de clases y el proyecto de desarrollo en Java del ejercicio de la OIA "Armando Móviles"

2020-06-06 21:54 UTC, delucas requested changes
@hlanzillotta @Federico-G 
Agregué comentarios. Me encanta la resolución, me gusta de hecho que no se llene el mapa de porquerías innecesarias: apenas se arma el móvil, elimina la clave.
Lo que puse es como para uniformar nuestro laburo. Muchos comentarios son simples, algunos requieren un poco más de laburo... pero en principio esto es muy bueno.

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/colgantes.in
> +3
Falta un enter final en este archivo

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/colgantes.out
> +6 1
Falta un enter final en este también

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/docs/DiagramaDeClases.drawio
> +<mxfile host="app.diagrams.net" modified="2020-06-04T17:26:14.925Z" agent="5.0 (Windows NT 6.1; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" etag="mV2w2UlDAmGhKyaq_c8g"
Está bueno poner el editable, pero pongamos tambien por favor un png exportado, para que se pueda visualizar sin instalar la herramienta

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/src/armadomoviles/Archivo.java
> +		ar = new Artesano();
No es necesario ahorrar caracteres en los nombres de variables :)

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/src/armadomoviles/Archivo.java
> +	public void setNombre(String nombre) {
¿Es necesario este setter?

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/src/armadomoviles/Artesano.java
> +		// Object priclave = colgantes.keySet().toArray()[0];//Obtener la primera clave
Yo sacaría estos comentarios de código que no se usó

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/src/armadomoviles/Movil.java
> +	private final int cantVarillas;
Para mí deberían llamarse `pesoColgante1`, `pesoColgante2` y `varillas`

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/src/armadomoviles/Movil.java
> +	public Movil(int pesocol1, int pesocol2) {
No estaría mal utilizar el mismo nombre que los atributos, para que sea más fácil hacer el mapeo mental.

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/src/armadomoviles/Movil.java
> +	public int retornarPesoTotal() {
Me queda la duda: si el ejercicio dice que cada móvil tiene el mismo peso de cada lado, ¿sería más simple multiplicar por dos?

2020-06-06 21:54 UTC, delucas commented on oia/armando-moviles/src/armadomoviles/ArmadoMoviles.java
> +        Archivo ar = new Archivo("colgantes.in");
Acá veo por qué usamos el setter... creo que sería más fácil que se inicialice con "colgantes", y dentro sepa que si está leyendo, es `.in`, y si está escribiendo, es `.out`.
¿Qué opinan?

2020-06-08 12:45 UTC, Federico-G commented on oia/armando-moviles/docs/DiagramaDeClases.drawio
> +<mxfile host="app.diagrams.net" modified="2020-06-04T17:26:14.925Z" agent="5.0 (Windows NT 6.1; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" etag="mV2w2UlDAmGhKyaq_c8g"
Está el png del diagrama también, ojo

2020-06-10 22:52 UTC, delucas approved these changes

2020-06-17 00:20 UTC, merged